---

working_directory: /tmp/linux-updating/
terraform:
  git_url: git.example.net/example/terraform.git
  username: example
  password: super-secret-password
ansible:
  git_url: git.example.net/example/ansible.git
  username: example
  password: super-secret-password
