---

working_directory: /tmp/linux-updating/
terraform:
  # For the poc we automaticlly add https:// to the git url, so please dont add it
  git_url: git.example.net/example/terraform.git
  username: example
  password: super-secret-password
ansible:
  # For the poc we automaticlly add https:// to the git url, so please dont add it
  git_url: git.example.net/example/ansible.git
  username: example
  password: super-secret-password
