---

working_directory: /tmp/linux-updating/
test_env:
  terraform:
    directory: infrastructure
    options: -auto-approve -var-file cf_auth.tfvars -var-file dns.tfvars -var-file do_auth.tfvars -var-file do.tfvars
prod_env:
  terraform:
    directory: infrastructure
    options: -auto-approve -var-file cf_auth.tfvars -var-file dns.tfvars -var-file do_auth.tfvars -var-file do.tfvars
